### ISSUE TITLE
Build failed on macos

### ISSUE THREAD

**Issue by putao0525** [gettext-rs/gettext-rs#121]
![image](https://github.com/Koka/gettext-rs/assets/12529019/a936be73-94a5-4e69-84b7-a6a233f4b0e7)
![image](https://github.com/Koka/gettext-rs/assets/12529019/3ab21264-8840-41ed-a485-99a5b51a00a9)

**Comment by putao0525** [comment]
![image](https://github.com/Koka/gettext-rs/assets/12529019/0a0670fa-037f-4dc0-b1e2-fc7a1bc8b40a)

**Comment by Minoru** [comment]
It's normal that you don't have `TARGET` in your shell; this variable is set by Cargo when running the build script: https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts 

Can you show the build log so I can see what error you're getting?

**Comment by jelmer** [comment]
FWIW I can reproduce this as well. Build log attached.
[build.log](https://github.com/user-attachments/files/15864611/build.log)

**Comment by putao0525** [comment]
I don't understand English very well.
I've solved the problem。 
This problem is because my macos is a newer version。 
The system already has the library installed, but build.rs can't find the class for that system. 
My solution was to rebuild build.rs
but , There are a lot of upwarps()  in build.rs, which is not recommended

**Comment by putao0525** [comment]
解决办法：
    println!("cargo:rustc-link-lib=framework=CoreFoundation");
    println!("cargo:rustc-link-lib=dylib=iconv");
    println!("cargo:rustc-link-lib=static=intl");
    println!("cargo:rustc-link-search=native={}/lib", "/opt/homebrew/opt/gettext");
    println!("cargo:lib={}/lib", "opt/homebrew/opt/gettext");
    println!("cargo:include={}/include", "/opt/homebrew/opt/gettext");
    println!("cargo:bin={}/bin", "opt/homebrew/opt/gettext");
    println!("cargo:root={}", "opt/homebrew/opt/gettext");

**Comment by Minoru** [comment]
@jeimer Ah, it's the same failure at #114. I hope to go through all the issues in this repo in July and make a new release; I think I'll just disable that warning.

**Comment by jelmer** [comment]
@Minoru or apparently #119 resolves it as well? It would be good to get that merged.

**Comment by jelmer** [comment]
Can confirm that #119 addresses the issue.

**Comment by Minoru** [comment]
I just published gettext-sys 0.21.4 that includes a fix for this.
